version: '3'

services:
  app:
    build:
      context: .
    command: /bin/sh -c "rm -f /nayami2/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/nayami2
      - public-data:/nayami2/public
      - tmp-data:/nayami2/tmp
      - log-data:/nayami2/log
    depends_on: 
      - db
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  
  
      
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docker_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/nayami2/public
      - tmp-data:/nayami2/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
