version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docker_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3305:3306"
    command: --default-authentication-plugin=mysql_native_password
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /nayami2/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/nayami2
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpacker

  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/nayami2
    ports:
      - '3035:3035'
